# Generated by Django 3.2.10 on 2023-08-10 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCallNotification',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('Station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
