# Generated by Django 3.2.10 on 2023-08-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_taxicallnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxiCallNotification',
        ),
    ]
