# Generated by Django 3.2.10 on 2023-08-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_userprofile_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_calls_as_client', to='profiles.userprofile')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxi_calls_as_driver', to='profiles.userprofile')),
            ],
        ),
    ]
