# Generated by Django 3.2.10 on 2023-08-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_taxicall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coins',
            field=models.PositiveIntegerField(default=4, null=True),
        ),
    ]
