# Generated by Django 3.2.10 on 2023-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_userprofile_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
